config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /fr/ do
    root 'appointments#index'
    resources :appointments, only: %i[index create show update destroy], path: '/'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  validates :start_at, uniqueness: true

  scope :up_comings, ->(nb_days) {
                       where('start_at >= ? AND start_at < ?',
                             Time.zone.now,
                             Time.zone.now + nb_days.days).order(start_at: :asc)
                     }

  def self.next
    next_appointment = Time.zone.now.to_date
    next_appointment += 1.day while find_by(start_at: next_appointment)
    next_appointment
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[update destroy]

  def index
    @appointments = Appointment.up_comings(60)
    @appointment = Appointment.new
    @next_appointment = Appointment.next
    @dates_to_disable = @appointments.pluck(:start_at)
  end

  def create
    redirect_to appointments_path if Appointment.create(appointment_params)
  end

  def update
    redirect_to appointments_path if @appointment.update(appointment_params)
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:start_at)
  end
end

app/views/appointments/_appointment.html.erb
<div class="row my-3 align-items-center">
  <div class="col-sm-11">
    <%= render "datepicker", appointment: appointment, dates_to_disable: @dates_to_disable %>
  </div>
  <%= link_to appointment_path(appointment),
      method: :delete,
      remote: true,
      class: "btn btn-danger col-sm-1" do %>
      <i class="fas fa-times"></i>
  <% end %>
</div>

app/views/appointments/_datepicker.html.erb
<%= form_with model: appointment do |f| %>
  <%= f.text_field :start_at,
      placeholder: t(".select"),
      data: {
        controller: "flatpickr",
        flatpickr_alt_format: t("date.formats.long"),
        flatpickr_default_date: appointment.start_at,
        flatpickr_locale: locale,
        flatpickr_min_date: Time.zone.now,
        flatpickr_max_date: Time.zone.now + 60.days,
        flatpickr_disable: dates_to_disable - [appointment.start_at]
      } %>
<% end %>

app/views/appointments/index.html.erb
<div class="container my-5">
  <h2 class="text-center text-primary mb-5"><%= t ".title" %></h3>
  <div class="row">
    <div class="col-md-6">
      <h3><%= t ".add" %></h3>
      <div class="my-3">
        <%= render "datepicker", appointment: @appointment, dates_to_disable: @dates_to_disable %>
      </div>
      <p class="text-secondary"><%= t(".next_appointment", next_at: l(@next_appointment, format: :long)) %></p>
    </div>
    <div class="col-md-6">
      <h3><%= t ".appointments" %></h3>
      <%= render @appointments %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Stimulus Flatpickr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/language" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_language.html.erb
<div class="container mt-1">
  <div class="row justify-content-end">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to "English", appointments_path(locale: ""),
          class: "btn btn-sm btn-primary #{locale == :en ? "disabled" : ""}" %>
      <%= link_to "Français", appointments_path(locale: :fr),
          class: "btn btn-sm btn-primary #{locale == :fr ? "disabled" : ""}" %>
    </div>
  </div>
</div>